version: '3.5'

services:
  kudu-master-1:
    image: apache/kudu:1.15
    container_name: kudu-master-1
    ports:
      - 7051
      - 8051
    command: ["master"]
    environment:
      - KUDU_MASTERS=kudu-master-1:7051
    networks:
      - csgo-net
  kudu-tserver:
    image: apache/kudu:1.15
    depends_on:
      - kudu-master-1
    ports:
      - 7050
      - 8050
    command: ["tserver"]
    environment:
      - KUDU_MASTERS=kudu-master-1:7051
    networks:
      - csgo-net
    deploy:
      replicas: 3
  impala:
    image: apache/kudu:impala-latest
    platform: linux/amd64
    container_name: impala
    depends_on:
      - kudu-master-1
    command: ["impala"]
    environment:
      - KUDU_MASTERS=kudu-master-1:7051
    networks:
      - csgo-net
  pyspark-notebook:
    image: jupyter/pyspark-notebook
    container_name: pyspark-notebook
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - csgo-net
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474
      - 7687
    networks:
      - csgo-net
    environment:
      - NEO4J_AUTH=none

networks:
  csgo-net:
    name: csgo-net
    driver: bridge